<?php
/**
 * Страница "Редактирование описание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма редактирования описания</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/desc-form.png' ?>" />
    </div>
    <p>Форма появляется после выбора пункта <b>"Редактировать описание"</b> контекстного меню выбранной записи шаблона.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Название.</b>Название шаблона;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Название в коде.</b> Название указываемое при вызове шаблона из приложения;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Описание.</b> Описание шаблона;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Вид.</b> Вид шаблона, то что шаблон выводит (каталог, страница, статья...);</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Назначение.</b> Назначение шаблона для сайта или Панели управления;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Язык.</b> Выбор языка шаблона, если шаблон не использует язык по умолчанию.</li>
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Шаблон принадлежит.</b> Принадлежность шаблона: модулю, расширению модуля, виджету, плагину или автономный.</li>
    </ul>
</article>