<?php
/**
 * Страница "Редактирование описание".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Editing description</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/desc-form.png' ?>" />
    </div>
    <p>The form appears after selecting the <b>"Edit description"</b> item from the context menu of the selected template record.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> Template name;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name in code.</b> The name specified when calling the template from the application;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Description.</b> Template description;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Type.</b> The type of template, what the template outputs (catalog, page, article...);</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Use.</b> Using a template for a website or Control Panel;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Language.</b> Select the template language if the template does not use the default language;</li>
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Balongs to.</b> Whether the template belongs to a module, module extension, widget, plugin or standalone.</li>
    </ul>
</article>