<?php
/**
 * Страница "Список шаблонов".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Список шаблонов</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>В списке отображаются все шаблоны сайта и Панели управления.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>Название.</b> Название папки или имя файла шаблона;</li>
        <li><b>Вид.</b> Вид шаблона (каталог, страница, статья...);</li>
        <li><b>Путь / файл.</b> Локальный путь к шаблону относительно выбранной темы;</li>
        <li><b>Название в коде.</b> Название указываемое при вызове шаблона из приложения;</li>
        <li><b>Права доступа.</b> Права доступа на запись и чтение файла шаблона;</li>
        <li><b>Время доступа.</b> Дата и время создания файла шаблона;</li>
        <li><b>Время правки.</b> Дата и время последнего изменения файла шаблона;</li>
        <li><b>Принадлежность.</b> Принадлежность шаблона (модулю, плагину...);</li>
        <li><b>Назначение.</b> Назначение шаблона для сайта или Панели управления;</li>
        <li><b>Язык.</b> Если в названии файла шаблона указана локализация, то должен отображаться язык.</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Удалить.</b> Удаляет выделенные шаблоны темы;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Очистить.</b> Удаляет все шаблоны темы;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Правка.</b> Вызывает форму для редактирования описания шаблона;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Выделить.</b> Выделяет или убирает выделение шаблонов;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список шаблонов;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-execute.svg' ?>" /> <b>Выполнить.</b> Создаёт описание или копию файлов шаблонов;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации о выбранном шаблоне;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Показать / Скрыть.</b> Показывает или скрывает столбцы;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Вызывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Фильтр.</b> Вызывает форму фильтрации записей в списке.</li>
    </ul>
</article>