<?php
/**
 * Страница "Список шаблонов".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>List of templates</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>The list displays all site templates and Control Panels.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>Name.</b> Folder name or template file name;</li>
        <li><b>Type.</b> Template type (catalog, page, article...);</li>
        <li><b>Path / file.</b> Local path to the template relative to the selected theme;</li>
        <li><b>Name in code.</b> The name specified when calling the template from the application;</li>
        <li><b>Permissions.</b> Permissions to write and read the template file;</li>
        <li><b>Access time.</b> Date and time the template file was created;</li>
        <li><b>Editing time.</b> Date and time the template file was last modified;</li>
        <li><b>Belongs.</b> Belongs to the template (module, plugin...);</li>
        <li><b>Use.</b> The template is used for the site or Control Panel;</li>
        <li><b>Language.</b> If localization is specified in the name of the template file, then the language should be displayed.</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Delete.</b> Delete the selected theme templates;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Clear.</b> Delete all theme templates;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Edit.</b> Shows the form for editing the template description;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Select.</b> Selects or deselects templates;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refresh the list of templates;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-execute.svg' ?>" /> <b>Execute.</b> Creates a description or copy of template files;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands or collapses the Navigation Panel to display information about the selected template.;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Show / Hide.</b> Shows or hides columns;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Shows the help window for the current list.;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Filter.</b> Shows the form for filtering records in a list.</li>
    </ul>
</article>