<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Шаблоны</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Шаблоны страниц сайта и компонентов веб-приложения.</p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">Список шаблонов</a></li>
        <li><a href="<?= $url('description') ?>">Форма редактирования описания</a></li>
        <li><a href="<?= $url('template') ?>">Форма редактирования шаблона</a></li>
        <li><a href="<?= $url('rename') ?>">Форма переименования шаблона</a></li>
        <li><a href="<?= $url('permissions') ?>">Форма прав доступа к шаблону</a></li>
    </ul>
</article>