<?php
/**
 * Страница "Права доступа к шаблону".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */

?>
<article>
    <h1>Template permissions</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/permissions-form.png' ?>" />
    </div>
    <p>The access rights form appears after selecting the <b>"Permissions"</b> item from the context menu of the selected template record.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><b>Owner rights.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
        sed diam voluptua;</li>
        <li><b>Group rights.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
        sed diam voluptua;</li>
        <li><b>Public rights.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
        sed diam voluptua;</li>
        <li><b>Numeric value.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
</article>