<?php
/**
 * Страница "Права доступа к шаблону".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма прав доступа к шаблону</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/permissions-form.png' ?>" />
    </div>
    <p>Форма появляется после выбора пункта <b>"Права доступа"</b> контекстного меню выбранной записи шаблона.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Права владельца.</b> Установка разрешений (чтение, запись, выполнение) для владельца;</li>
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Групповые права.</b> Установка разрешений (чтение, запись, выполнение) для группы владельца;</li>
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Публичные права.</b> Установка разрешений (чтение, запись, выполнение) для всех остальных;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Числовое значение.</b> Числовое значение полученное из установки разрешений.</li>
    </ul>
</article>