<?php
/**
 * Страница "Права доступа к шаблону".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Template permissions</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/permissions-form.png' ?>" />
    </div>
    <p>The access rights form appears after selecting the <b>"Permissions"</b> item from the context menu of the selected template record.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Owner rights.</b> Set permissions (read, write, execute) for the owner;</li>
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Group rights.</b> Set permissions (read, write, execute) for the owner group;</li>
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Public rights.</b> Set permissions (read, write, execute) for everyone else;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Numeric value.</b> Numeric value obtained from setting permissions.</li>
    </ul>
</article>