<?php
/**
 * Страница "Переименование шаблона".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Renaming a template</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/rename-form.png' ?>" />
    </div>
    <p>The form appears after selecting the <b>"Rename"</b> item from the context menu of the selected template record.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>New name.</b> New template file name without path specification.</li>
    </ul>
</article>