<?php
/**
 * Страница "Переименование шаблона".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма переименования шаблона</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/rename-form.png' ?>" />
    </div>
    <p>Форма появляется после выбора пункта <b>"Переименовать"</b> контекстного меню выбранной записи шаблона.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Новое имя.</b> Новое имя файла шаблона без указания пути.</li>
    </ul>
</article>